import {todayDateStr,shiftDate} from './dates.js';

export const mkPdfId=()=>`pdf-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
export const mkAttachId=()=>`att-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
export const mkBookmarkId=()=>`bm-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
export const mkSpotId=()=>`spot-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
export const mkPerfId=()=>`perf-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;

export function getItemTime(t,id){const k=String(id);const pre=k+':';let total=0;for(const x in t){if(x===k||x.startsWith(pre))total+=t[x]||0;}return total;}
export function getSpotTime(t,id,sid){return t[`${id}:${sid}`]||0;}
export function getParentBucket(t,id){return t[String(id)]||0;}

export function displayTitle(i){if(i.collection&&i.movement)return `${i.collection} — ${i.movement}`;if(i.collection&&i.title&&i.title!==i.collection)return `${i.collection} — ${i.title}`;if(i.collection)return i.collection;if(i.movement)return i.movement;return i.title||'Untitled';}
export function formatByline(i){const p=[];if(i.composer)p.push(i.composer);if(i.arranger)p.push(`arr. ${i.arranger}`);if(i.author)p.push(i.author);return p.join(', ');}
export function formatForMarkdown(i){let base;if(i.collection&&i.movement){base=i.catalog?`${i.collection}, ${i.catalog} — ${i.movement}`:`${i.collection} — ${i.movement}`;}else if(i.collection){base=i.catalog?`${i.collection}, ${i.catalog}`:i.collection;}else{base=i.catalog?`${i.title||'Untitled'}, ${i.catalog}`:(i.title||'Untitled');}const by=formatByline(i);return by?`${base} (${by})`:base;}

export function resolveHistoryItem(e,items){
  const has=e.title!==undefined||e.type!==undefined||e.composer!==undefined;
  const live=items.find(i=>i.id===e.id);
  if(has){return {id:e.id,title:e.title||live?.title||'Untitled',composer:e.composer??live?.composer??'',arranger:e.arranger??live?.arranger??'',catalog:e.catalog??live?.catalog??'',collection:e.collection??live?.collection??'',movement:e.movement??live?.movement??'',type:e.type||live?.type||'piece',detail:live?.detail||'',note:e.note||'',spotMinutes:e.spotMinutes||{},spotsSnapshot:e.spotsSnapshot||[]};}
  if(!live)return null;
  return {id:live.id,title:live.title,composer:live.composer||'',arranger:live.arranger||'',catalog:live.catalog||'',collection:live.collection||'',movement:live.movement||'',type:live.type,detail:live.detail||'',note:'',spotMinutes:{},spotsSnapshot:[]};
}

export function buildHistoryItems(it,items){
  return items.filter(item=>{if((it[item.id]||0)>0)return true;const pre=`${item.id}:`;return Object.keys(it).some(k=>k.startsWith(pre)&&(it[k]||0)>0);}).map(item=>{
    const parent=it[item.id]||0;const spotSec={};const pre=`${item.id}:`;
    Object.keys(it).forEach(k=>{if(k.startsWith(pre)){const sid=k.slice(pre.length);if((it[k]||0)>0)spotSec[sid]=it[k];}});
    const snap=(item.spots||[]).filter(s=>spotSec[s.id]).map(s=>({id:s.id,label:s.label}));
    return {id:item.id,minutes:Math.floor((parent+Object.values(spotSec).reduce((a,b)=>a+b,0))/60),title:item.title,composer:item.composer||'',arranger:item.arranger||'',catalog:item.catalog||'',collection:item.collection||'',movement:item.movement||'',type:item.type,note:item.todayNote||'',spotMinutes:Object.fromEntries(Object.entries(spotSec).map(([k,v])=>[k,Math.floor(v/60)])),spotsSnapshot:snap};
  });
}

export function nextPerformance(perfs){if(!Array.isArray(perfs)||perfs.length===0)return null;const td=todayDateStr();const up=perfs.filter(p=>p.date&&p.date>=td).sort((a,b)=>a.date.localeCompare(b.date));if(up[0])return up[0];const past=perfs.filter(p=>p.date).sort((a,b)=>b.date.localeCompare(a.date));return past[0]||null;}
export function normalizeComposerKey(s){return (s||'').trim().toLowerCase().replace(/\s+/g,' ');}

export const mkNoteLogId=()=>`nl-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;

export const makeNewItem=(type)=>({id:Date.now()+Math.floor(Math.random()*1000),type,title:'Untitled',tags:[],pdfs:[],defaultPdfId:null,detail:'',composer:'',author:'',arranger:'',catalog:'',collection:'',movement:'',stage:'queued',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'',spots:[],performances:[],lengthSecs:null,noteLog:[]});

export const TEST_REPERTOIRE_ITEMS=[
  {id:'test-tech-001',type:'tech',title:'The Virtuoso Pianist: Exercise No. 1',tags:['hanon','finger independence'],pdfs:[],defaultPdfId:null,detail:'',composer:'Charles-Louis Hanon',author:'',arranger:'',catalog:'Part I, No. 1',collection:'The Virtuoso Pianist',movement:'Exercise No. 1',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:108,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:300},
  {id:'test-tech-002',type:'tech',title:'School of Velocity No. 1',tags:['czerny','velocity'],pdfs:[],defaultPdfId:null,detail:'',composer:'Carl Czerny',author:'',arranger:'',catalog:'Op. 299 No. 1',collection:'School of Velocity',movement:'No. 1',stage:'polishing',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:132,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:120},
  {id:'test-tech-003',type:'tech',title:'The Art of Finger Dexterity No. 2',tags:['czerny','dexterity'],pdfs:[],defaultPdfId:null,detail:'',composer:'Carl Czerny',author:'',arranger:'',catalog:'Op. 740 No. 2',collection:'The Art of Finger Dexterity',movement:'No. 2',stage:'queued',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:120,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:180},
  {id:'test-tech-004',type:'tech',title:'60 Selected Studies No. 1',tags:['cramer','study'],pdfs:[],defaultPdfId:null,detail:'',composer:'Johann Baptist Cramer',author:'',arranger:'Hans von Bulow',catalog:'No. 1',collection:'60 Selected Studies',movement:'No. 1',stage:'maintenance',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:96,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:240},
  {id:'test-tech-005',type:'tech',title:'51 Exercises No. 1',tags:['brahms','independence'],pdfs:[],defaultPdfId:null,detail:'',composer:'Johannes Brahms',author:'',arranger:'',catalog:'WoO 6 No. 1',collection:'51 Exercises',movement:'No. 1',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:80,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:210},
  {id:'test-tech-006',type:'tech',title:'Essential Finger Exercises No. 1',tags:['dohnanyi','coordination'],pdfs:[],defaultPdfId:null,detail:'',composer:'Erno Dohnanyi',author:'',arranger:'',catalog:'No. 1',collection:'Essential Finger Exercises',movement:'No. 1',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:72,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:300},
  {id:'test-tech-007',type:'tech',title:'Two-Part Invention No. 1 in C major',tags:['bach','counterpoint'],pdfs:[],defaultPdfId:null,detail:'',composer:'Johann Sebastian Bach',author:'',arranger:'',catalog:'BWV 772',collection:'Two-Part Inventions',movement:'No. 1 in C major',stage:'polishing',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:92,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:90},
  {id:'test-tech-008',type:'tech',title:'Mikrokosmos: From the Diary of a Fly',tags:['bartok','rhythm'],pdfs:[],defaultPdfId:null,detail:'',composer:'Bela Bartok',author:'',arranger:'',catalog:'Sz. 107 No. 142',collection:'Mikrokosmos',movement:'From the Diary of a Fly',stage:'queued',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:116,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:95},
  {id:'test-piece-001',type:'piece',title:'Piano Sonata No. 8 in C minor',tags:['classical','sonata'],pdfs:[],defaultPdfId:null,detail:'',composer:'Ludwig van Beethoven',author:'',arranger:'',catalog:'Op. 13',collection:'Piano Sonata No. 8 in C minor',movement:'I. Grave - Allegro di molto e con brio',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:540},
  {id:'test-piece-002',type:'piece',title:'Nocturne in E-flat major',tags:['romantic','nocturne'],pdfs:[],defaultPdfId:null,detail:'',composer:'Frederic Chopin',author:'',arranger:'',catalog:'Op. 9 No. 2',collection:'',movement:'',stage:'maintenance',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:270},
  {id:'test-piece-003',type:'piece',title:'Clair de lune',tags:['impressionist','debussy'],pdfs:[],defaultPdfId:null,detail:'',composer:'Claude Debussy',author:'',arranger:'',catalog:'L. 75 No. 3',collection:'Suite bergamasque',movement:'III. Clair de lune',stage:'polishing',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:300},
  {id:'test-piece-004',type:'piece',title:'Piano Sonata No. 11 in A major',tags:['classical','mozart'],pdfs:[],defaultPdfId:null,detail:'',composer:'Wolfgang Amadeus Mozart',author:'',arranger:'',catalog:'K. 331',collection:'Piano Sonata No. 11 in A major',movement:'I. Andante grazioso',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:780},
  {id:'test-piece-005',type:'piece',title:'Prelude and Fugue in C major',tags:['baroque','bach'],pdfs:[],defaultPdfId:null,detail:'',composer:'Johann Sebastian Bach',author:'',arranger:'',catalog:'BWV 846',collection:'The Well-Tempered Clavier, Book I',movement:'Prelude and Fugue in C major',stage:'maintenance',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:240},
  {id:'test-piece-006',type:'piece',title:'Traumerei',tags:['romantic','character piece'],pdfs:[],defaultPdfId:null,detail:'',composer:'Robert Schumann',author:'',arranger:'',catalog:'Op. 15 No. 7',collection:'Kinderszenen',movement:'VII. Traumerei',stage:'queued',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:180},
  {id:'test-piece-007',type:'piece',title:'Prelude in C-sharp minor',tags:['romantic','prelude'],pdfs:[],defaultPdfId:null,detail:'',composer:'Sergei Rachmaninoff',author:'',arranger:'',catalog:'Op. 3 No. 2',collection:'Morceaux de fantaisie',movement:'Prelude in C-sharp minor',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:240},
  {id:'test-piece-008',type:'piece',title:'Liebestraum No. 3',tags:['romantic','liszt'],pdfs:[],defaultPdfId:null,detail:'',composer:'Franz Liszt',author:'',arranger:'',catalog:'S. 541 No. 3',collection:'Liebestraume',movement:'No. 3 in A-flat major',stage:'polishing',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:300},
  {id:'test-play-001',type:'play',title:'The Entertainer',tags:['ragtime','joplin'],pdfs:[],defaultPdfId:null,detail:'',composer:'Scott Joplin',author:'',arranger:'',catalog:'',collection:'',movement:'',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:210},
  {id:'test-play-002',type:'play',title:'Maple Leaf Rag',tags:['ragtime','joplin'],pdfs:[],defaultPdfId:null,detail:'',composer:'Scott Joplin',author:'',arranger:'',catalog:'',collection:'',movement:'',stage:'queued',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:180},
  {id:'test-play-003',type:'play',title:'Summertime',tags:['jazz','gershwin'],pdfs:[],defaultPdfId:null,detail:'',composer:'George Gershwin',author:'',arranger:'',catalog:'from Porgy and Bess',collection:'Porgy and Bess',movement:'Summertime',stage:'maintenance',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:160},
  {id:'test-play-004',type:'play',title:'Take the A Train',tags:['jazz','standard'],pdfs:[],defaultPdfId:null,detail:'',composer:'Billy Strayhorn',author:'',arranger:'',catalog:'',collection:'',movement:'',stage:'polishing',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:190},
  {id:'test-play-005',type:'play',title:'River Flows in You',tags:['contemporary','yiruma'],pdfs:[],defaultPdfId:null,detail:'',composer:'Yiruma',author:'',arranger:'',catalog:'',collection:'First Love',movement:'River Flows in You',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:185},
  {id:'test-play-006',type:'play',title:"One Summer's Day",tags:['film','hisaishi'],pdfs:[],defaultPdfId:null,detail:'',composer:'Joe Hisaishi',author:'',arranger:'',catalog:'from Spirited Away',collection:'Spirited Away',movement:"One Summer's Day",stage:'queued',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:240},
  {id:'test-play-007',type:'play',title:'Nuvole Bianche',tags:['contemporary','einaudi'],pdfs:[],defaultPdfId:null,detail:'',composer:'Ludovico Einaudi',author:'',arranger:'',catalog:'',collection:'Una mattina',movement:'Nuvole Bianche',stage:'maintenance',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'piano',spots:[],performances:[],lengthSecs:360},
  {id:'test-study-001',type:'study',title:'Harmony',tags:['theory','harmony'],pdfs:[],defaultPdfId:null,detail:'',composer:'',author:'Walter Piston',arranger:'',catalog:'',collection:'',movement:'',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'',spots:[],performances:[],lengthSecs:null},
  {id:'test-study-002',type:'study',title:'Theory of Harmony',tags:['theory','harmony'],pdfs:[],defaultPdfId:null,detail:'',composer:'',author:'Arnold Schoenberg',arranger:'',catalog:'',collection:'',movement:'',stage:'queued',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'',spots:[],performances:[],lengthSecs:null},
  {id:'test-study-003',type:'study',title:'Gradus ad Parnassum',tags:['counterpoint','species'],pdfs:[],defaultPdfId:null,detail:'',composer:'',author:'Johann Joseph Fux',arranger:'',catalog:'',collection:'',movement:'',stage:'polishing',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'',spots:[],performances:[],lengthSecs:null},
  {id:'test-study-004',type:'study',title:'Essay on the True Art of Playing Keyboard Instruments',tags:['performance practice','keyboard'],pdfs:[],defaultPdfId:null,detail:'',composer:'',author:'Carl Philipp Emanuel Bach',arranger:'',catalog:'',collection:'',movement:'',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'keyboard',spots:[],performances:[],lengthSecs:null},
  {id:'test-study-005',type:'study',title:'Behind Bars',tags:['notation','engraving'],pdfs:[],defaultPdfId:null,detail:'',composer:'',author:'Elaine Gould',arranger:'',catalog:'',collection:'',movement:'',stage:'queued',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'',spots:[],performances:[],lengthSecs:null},
  {id:'test-study-006',type:'study',title:'The Study of Orchestration',tags:['orchestration','instrumentation'],pdfs:[],defaultPdfId:null,detail:'',composer:'',author:'Samuel Adler',arranger:'',catalog:'',collection:'',movement:'',stage:'maintenance',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'',spots:[],performances:[],lengthSecs:null},
  {id:'test-study-007',type:'study',title:'Counterpoint',tags:['counterpoint','textbook'],pdfs:[],defaultPdfId:null,detail:'',composer:'',author:'Kent Kennan',arranger:'',catalog:'',collection:'',movement:'',stage:'learning',referenceUrl:'',startedDate:null,bpmLog:[],bpmTarget:null,todayNote:'',instrument:'',spots:[],performances:[],lengthSecs:null},
];

export const calcStreak=(history,effMin)=>{const map={};history.forEach(h=>{if((h.kind==='day'||!h.kind)){const eff=(h.minutes||0)-(h.warmupMinutes||0);if(eff>=1)map[h.date]=eff;}});const t=todayDateStr();if((effMin||0)>=1)map[t]=effMin;let c=0;let cur=t;if(!map[cur])cur=shiftDate(cur,-1);while(map[cur]){c++;cur=shiftDate(cur,-1);}return c;};
