import React, {useState, useEffect} from 'react';
import {FileText, Upload, Plus, X, Pause, Play, Bookmark, Music, Crosshair} from 'lucide-react';
import {BG, SURFACE, SURFACE2, TEXT, MUTED, FAINT, DIM, LINE, LINE_MED, LINE_STR, IKB, IKB_SOFT, serif} from '../constants/theme.js';
import {displayTitle, formatByline, getItemTime} from '../lib/items.js';
import {SpotRow} from './shared.jsx';

export default function PdfDrawer({pdfItem,items,pdfUrlMap,itemTimes,activeItemId,activeSpotId,startItem,stopItem,updateItem,addPdfToItem,removePdfFromItem,renamePdf,setDefaultPdf,fmt,setPromptModal,setConfirmModal,onClose,dayClosed,addSpot,updateSpot,deleteSpot,editSpotTime}){
  const [activePdfId,setActivePdfId]=useState(pdfItem.defaultPdfId||pdfItem.pdfs?.[0]?.id||null);
  const [dragOver,setDragOver]=useState(false);const [renamingId,setRenamingId]=useState(null);const [renameVal,setRenameVal]=useState('');
  useEffect(()=>{if(!pdfItem.pdfs||pdfItem.pdfs.length===0){setActivePdfId(null);return;}if(!pdfItem.pdfs.some(p=>p.id===activePdfId))setActivePdfId(pdfItem.defaultPdfId||pdfItem.pdfs[0].id);},[pdfItem.pdfs,pdfItem.defaultPdfId,activePdfId]);
  const activePdf=pdfItem.pdfs?.find(p=>p.id===activePdfId);const activeUrl=activePdf?pdfUrlMap[activePdf.id]:null;const atLimit=(pdfItem.pdfs||[]).length>=5;
  const handleFile=async(file)=>{if(!file||file.type!=='application/pdf'){setConfirmModal&&setConfirmModal({message:'Please select a PDF file.',confirmLabel:'OK',onConfirm:()=>setConfirmModal(null)});return;}if(atLimit){setConfirmModal&&setConfirmModal({message:'Up to 5 PDFs per piece.',confirmLabel:'OK',onConfirm:()=>setConfirmModal(null)});return;}const id=await addPdfToItem(pdfItem.id,file,file.name.replace(/\.pdf$/i,''));if(id)setActivePdfId(id);};
  const onDrop=(e)=>{e.preventDefault();setDragOver(false);const f=e.dataTransfer.files?.[0];if(f)handleFile(f);};
  const onInputChange=(e)=>{const f=e.target.files?.[0];if(f)handleFile(f);e.target.value='';};
  const startRename=(p)=>{setRenamingId(p.id);setRenameVal(p.name);};
  const commitRename=()=>{if(renamingId&&renameVal.trim())renamePdf(pdfItem.id,renamingId,renameVal.trim());setRenamingId(null);};
  const confirmRemove=(p)=>{setConfirmModal&&setConfirmModal({message:`Remove "${p.name}"?`,confirmLabel:'Remove',onConfirm:()=>{setConfirmModal(null);removePdfFromItem(pdfItem.id,p.id);}});};
  const isActiveWhole=activeItemId===pdfItem.id&&!activeSpotId;const isActiveAny=activeItemId===pdfItem.id;const spots=pdfItem.spots||[];

  return (<div className="fixed inset-0 z-50 flex items-center justify-center p-6" style={{background:'rgba(0,0,0,0.85)',backdropFilter:'blur(8px)'}}><div className="absolute inset-0" onClick={onClose}/><div className="relative w-full h-full max-w-7xl flex flex-col" style={{background:BG,border:`1px solid ${LINE_STR}`,boxShadow:'0 20px 60px rgba(0,0,0,0.8)'}}>
    <div className="flex items-center justify-between px-6 py-4 gap-3 shrink-0" style={{borderBottom:`1px solid ${LINE_MED}`}}>
      <div className="min-w-0 flex-1"><div className="uppercase" style={{color:FAINT,fontSize:'10px',letterSpacing:'0.32em'}}>Score</div><h3 className="text-xl mt-0.5 truncate" style={{fontFamily:serif,fontWeight:300}}>{formatByline(pdfItem)&&<span className="italic" style={{color:MUTED}}>{formatByline(pdfItem)} — </span>}{displayTitle(pdfItem)}{pdfItem.catalog&&<span className="italic ml-2" style={{color:FAINT,fontSize:'14px'}}>{pdfItem.catalog}</span>}{pdfItem.instrument&&<span className="uppercase ml-3" style={{color:FAINT,fontSize:'10px',letterSpacing:'0.22em'}}>· {pdfItem.instrument}</span>}</h3>{pdfItem.referenceUrl&&<a href={pdfItem.referenceUrl} target="_blank" rel="noopener noreferrer" className="uppercase flex items-center gap-1.5 mt-1" style={{color:IKB,fontSize:'9px',letterSpacing:'0.22em'}}><Music className="w-3 h-3" strokeWidth={1.25}/> Reference recording ↗</a>}</div>
      <div className="flex items-center gap-3 shrink-0"><button onClick={()=>{isActiveAny?stopItem():startItem(pdfItem.id);}} disabled={dayClosed&&!isActiveAny} className="uppercase px-3 py-2 flex items-center gap-1.5" style={isActiveWhole?{background:IKB,color:TEXT,border:`1px solid ${IKB}`,boxShadow:`0 0 15px ${IKB}60`,fontSize:'10px',letterSpacing:'0.22em'}:{background:'transparent',color:dayClosed?FAINT:TEXT,border:`1px solid ${LINE_STR}`,fontSize:'10px',letterSpacing:'0.22em',cursor:(dayClosed&&!isActiveAny)?'not-allowed':'pointer'}}>{isActiveAny?<><Pause className="w-3 h-3" strokeWidth={1.25}/> Pause</>:<><Play className="w-3 h-3" strokeWidth={1.25}/> {dayClosed?'Closed':'Whole piece'}</>}</button><button onClick={onClose} style={{color:MUTED}}><X className="w-4 h-4" strokeWidth={1.25}/></button></div>
    </div>
    {(pdfItem.pdfs||[]).length>0&&(<div className="flex items-center gap-0 overflow-x-auto etudes-scroll shrink-0" style={{borderBottom:`1px solid ${LINE}`,background:SURFACE}}>{pdfItem.pdfs.map(p=>{const active=p.id===activePdfId;const isD=p.id===pdfItem.defaultPdfId;const ren=renamingId===p.id;return (<div key={p.id} className="group flex items-center gap-2 px-4 py-2.5 shrink-0" style={{borderRight:`1px solid ${LINE}`,borderBottom:active?`2px solid ${IKB}`:'2px solid transparent',background:active?IKB_SOFT:'transparent',cursor:ren?'default':'pointer'}} onClick={()=>{if(!ren)setActivePdfId(p.id);}} onDoubleClick={()=>startRename(p)}>{isD&&<Bookmark className="w-3 h-3" strokeWidth={1.25} style={{color:IKB}}/>}{ren?(<input autoFocus value={renameVal} onChange={e=>setRenameVal(e.target.value)} onBlur={commitRename} onKeyDown={e=>{if(e.key==='Enter')commitRename();else if(e.key==='Escape')setRenamingId(null);}} onClick={e=>e.stopPropagation()} className="focus:outline-none px-1" style={{background:SURFACE2,color:TEXT,border:`1px solid ${LINE_MED}`,fontSize:'12px',width:'120px'}}/>):(<span style={{fontSize:'12px',fontWeight:active?400:300,color:active?TEXT:MUTED,maxWidth:'180px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{p.name}</span>)}{active&&!ren&&(<div className="flex items-center gap-1"><button onClick={e=>{e.stopPropagation();startRename(p);}} className="opacity-0 group-hover:opacity-100" style={{color:FAINT,fontSize:'9px',letterSpacing:'0.2em'}}>edit</button>{!isD&&<button onClick={e=>{e.stopPropagation();setDefaultPdf(pdfItem.id,p.id);}} className="opacity-0 group-hover:opacity-100" style={{color:FAINT}}><Bookmark className="w-3 h-3" strokeWidth={1.25}/></button>}<button onClick={e=>{e.stopPropagation();confirmRemove(p);}} className="opacity-0 group-hover:opacity-100" style={{color:FAINT}}><X className="w-3 h-3" strokeWidth={1.25}/></button></div>)}</div>);})}{!atLimit&&(<label className="flex items-center gap-1.5 px-4 py-2.5 cursor-pointer shrink-0" style={{color:FAINT,fontSize:'11px',letterSpacing:'0.2em'}}><Plus className="w-3 h-3" strokeWidth={1.25}/> Add PDF<input type="file" accept="application/pdf" className="hidden" onChange={onInputChange}/></label>)}<div className="ml-auto px-4 py-2.5 uppercase shrink-0" style={{color:DIM,fontSize:'9px',letterSpacing:'0.22em'}}>{pdfItem.pdfs.length}/5</div></div>)}
    <div className="flex-1 flex overflow-hidden">
      <div className="flex-1 relative overflow-hidden" style={{background:'rgba(255,255,255,0.02)'}} onDragOver={e=>{e.preventDefault();setDragOver(true);}} onDragLeave={()=>setDragOver(false)} onDrop={onDrop}>
        {activeUrl?(<div className="w-full h-full flex items-center justify-center p-6"><iframe src={activeUrl} className="w-full h-full max-w-5xl border-0" title="Score" style={{background:'#fff'}}/></div>):(<div className="h-full flex flex-col items-center justify-center p-8 text-center"><FileText className="w-10 h-10 mb-5" strokeWidth={1} style={{color:DIM}}/><p className="uppercase mb-3" style={{color:FAINT,fontSize:'10px',letterSpacing:'0.32em'}}>No score attached</p><p className="text-sm mb-6 max-w-sm italic" style={{color:MUTED,fontFamily:serif,fontSize:'15px',lineHeight:1.6}}>Upload a PDF or drag one here.</p><label className="px-4 py-2 uppercase cursor-pointer flex items-center gap-2" style={{background:IKB,color:TEXT,boxShadow:`0 0 20px ${IKB}40`,fontSize:'10px',letterSpacing:'0.22em'}}><Upload className="w-3 h-3" strokeWidth={1.25}/> Upload PDF<input type="file" accept="application/pdf" className="hidden" onChange={onInputChange}/></label></div>)}
        {dragOver&&(<div className="absolute inset-0 flex items-center justify-center pointer-events-none" style={{background:`${IKB}20`,border:`2px dashed ${IKB}`,boxShadow:`inset 0 0 40px ${IKB}30`}}><div className="px-6 py-4 flex items-center gap-3" style={{background:BG,border:`1px solid ${IKB}`}}><Upload className="w-5 h-5" strokeWidth={1.25} style={{color:IKB}}/><span className="uppercase" style={{color:TEXT,fontSize:'11px',letterSpacing:'0.28em'}}>Drop to upload PDF</span></div></div>)}
      </div>
      <div className="w-80 flex flex-col shrink-0 overflow-hidden" style={{borderLeft:`1px solid ${LINE_MED}`}}>
        <div className="px-5 py-4 shrink-0" style={{borderBottom:`1px solid ${LINE}`}}><div className="uppercase" style={{color:FAINT,fontSize:'10px',letterSpacing:'0.28em'}}>Today</div><div className="text-xs font-mono tabular-nums mt-1" style={{color:MUTED,fontWeight:300}}>{fmt(getItemTime(itemTimes,pdfItem.id))}</div></div>
        <div className="flex-1 overflow-auto etudes-scroll">
          <div className="px-5 py-4" style={{borderBottom:`1px solid ${LINE}`}}>
            <div className="uppercase mb-3 flex items-center gap-1.5" style={{color:FAINT,fontSize:'10px',letterSpacing:'0.28em'}}><Crosshair className="w-3 h-3" strokeWidth={1.25} style={{color:IKB}}/> Spots {spots.length>0&&<span style={{color:DIM,letterSpacing:'0.22em'}}>· {spots.length}</span>}</div>
            {spots.length>0&&(<div style={{background:SURFACE2,border:`1px solid ${LINE}`}}>{spots.map((s,idx)=>(<div key={s.id} style={{borderBottom:idx<spots.length-1?`1px solid ${LINE}`:'none'}}><SpotRow spot={s} itemId={pdfItem.id} itemTimes={itemTimes} isActive={activeItemId===pdfItem.id&&activeSpotId===s.id} onStart={()=>startItem(pdfItem.id,s.id)} onStop={stopItem} onRename={(label)=>updateSpot(pdfItem.id,s.id,{label})} onDelete={()=>deleteSpot(pdfItem.id,s.id)} onEditTime={editSpotTime?(v)=>editSpotTime(pdfItem.id,s.id,v):undefined} dayClosed={dayClosed} compact/></div>))}</div>)}
            <button onClick={()=>addSpot(pdfItem.id,'New spot')} className="uppercase flex items-center gap-1.5 mt-2 italic" style={{color:MUTED,fontFamily:serif,fontSize:'12px'}}><Plus className="w-3 h-3 not-italic" strokeWidth={1.25}/> Add spot</button>
          </div>
          <textarea value={pdfItem.todayNote||''} onChange={e=>updateItem(pdfItem.id,{todayNote:e.target.value})} placeholder="Today's session notes…" className="w-full h-40 p-5 resize-none focus:outline-none" style={{background:'transparent',color:TEXT,fontFamily:serif,fontSize:'14px',lineHeight:1.7,fontWeight:300,borderBottom:`1px solid ${LINE}`}}/>
          <div className="px-5 py-3" style={{borderBottom:`1px solid ${LINE}`}}><div className="uppercase" style={{color:FAINT,fontSize:'10px',letterSpacing:'0.28em'}}>Notes <span style={{color:DIM,letterSpacing:'0.2em'}}>· persistent</span></div></div>
          <textarea value={pdfItem.detail} onChange={e=>updateItem(pdfItem.id,{detail:e.target.value})} placeholder="Long-running notes…" className="w-full h-40 p-5 resize-none focus:outline-none" style={{background:'transparent',color:TEXT,fontFamily:serif,fontSize:'14px',lineHeight:1.7,fontWeight:300}}/>
        </div>
      </div>
    </div>
  </div></div>);
}
