import React, {useState, useEffect, useRef} from 'react';
import {Play, Pause, Plus, X, ChevronDown, ChevronUp, ArrowUp, ArrowDown, Crosshair, Pencil, Check, Music, Calendar} from 'lucide-react';
import {BG, SURFACE, SURFACE2, TEXT, MUTED, FAINT, DIM, LINE, LINE_MED, LINE_STR, IKB, IKB_SOFT, WARM, serif, serifText, sans, mono} from '../constants/theme.js';
import {STAGES} from '../constants/config.js';
import {idbGet} from '../lib/storage.js';
import {daysUntil} from '../lib/dates.js';
import {getItemTime, getSpotTime, displayTitle, formatByline} from '../lib/items.js';

export function DisplayHeader({eyebrow,title,suffix,right,titleRight}){return (<div className="mb-12 flex items-end justify-between gap-6"><div><div className="uppercase mb-3" style={{color:FAINT,fontSize:'10px',letterSpacing:'0.32em'}}>{eyebrow}</div><div className="flex items-end gap-5"><h1 className="leading-none" style={{fontFamily:serif,fontWeight:300,fontSize:'72px',letterSpacing:'-0.02em'}}><span style={{fontStyle:'italic'}}>{title}</span>{suffix&&<span style={{color:FAINT}}>{suffix}</span>}</h1>{titleRight&&<div className="pb-2">{titleRight}</div>}</div></div>{right}</div>);}

export function Ring({value,max,maxSize=180}){const pct=Math.min(100,(value/max)*100);return (<div className="relative flex items-center justify-center w-full mx-auto" style={{maxWidth:maxSize,aspectRatio:'1 / 1'}}><svg viewBox="0 0 100 100" className="w-full h-full -rotate-90" preserveAspectRatio="xMidYMid meet"><circle cx="50" cy="50" r="44" fill="none" stroke={LINE_MED} strokeWidth="5"/><circle cx="50" cy="50" r="44" fill="none" stroke={IKB} strokeWidth="5" strokeLinecap="round" strokeDasharray={2*Math.PI*44} strokeDashoffset={2*Math.PI*44*(1-pct/100)} style={{transition:'stroke-dashoffset 0.6s ease'}}/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><div className="tabular-nums" style={{fontFamily:serif,fontWeight:300,letterSpacing:'-0.02em',fontSize:'36px'}}>{value}<span style={{color:MUTED,fontSize:'18px'}}>′</span></div><div className="uppercase mt-1" style={{color:FAINT,fontSize:'9px',letterSpacing:'0.25em'}}>of {max}′</div></div></div>);}

export function StageLabels({stage,onChange,compact=false}){const ai=STAGES.findIndex(s=>s.key===stage);return (<div className={`flex ${compact?'gap-4':'gap-5'} flex-wrap`}>{STAGES.map((s,i)=>{const a=i===ai;return (<button key={s.key} onClick={(e)=>{e.stopPropagation();onChange(s.key);}} className="transition pb-1.5" style={{color:a?TEXT:FAINT,fontFamily:serif,fontStyle:'italic',fontSize:compact?'12px':'15px',fontWeight:300,borderBottom:a?`1px solid ${IKB}`:`1px solid transparent`}}>{s.label}</button>);})}</div>);}

export function Waveform({date,meta,compact=false}){const [playing,setPlaying]=useState(false);const [progress,setProgress]=useState(0);const [blobAvailable,setBlobAvailable]=useState(true);const audioRef=useRef(null);const urlRef=useRef(null);
  useEffect(()=>{if(!meta)return;idbGet('recordings',date).then(b=>setBlobAvailable(!!b));},[date,meta]);const ensure=async()=>{if(audioRef.current)return audioRef.current;const b=await idbGet('recordings',date);if(!b)return null;urlRef.current=URL.createObjectURL(b);const a=new Audio(urlRef.current);a.ontimeupdate=()=>setProgress(a.duration?a.currentTime/a.duration:0);a.onended=()=>{setPlaying(false);setProgress(0);};audioRef.current=a;return a;};const toggle=async()=>{const a=await ensure();if(!a)return;if(playing){a.pause();setPlaying(false);}else{a.play().then(()=>setPlaying(true)).catch(()=>{});}};useEffect(()=>()=>{if(audioRef.current)audioRef.current.pause();if(urlRef.current)URL.revokeObjectURL(urlRef.current);},[]);const peaks=meta?.peaks||[];const h=compact?20:32;if(!blobAvailable&&meta)return(<div className="flex items-center gap-2" style={{color:FAINT}}><span className="meta" style={{fontSize:'10px',letterSpacing:'0.14em',textTransform:'uppercase'}}>Recording on another device</span></div>);return (<div className="flex items-center gap-3 w-full" style={{minWidth:0}}><button onClick={toggle} className="shrink-0" style={{color:playing?IKB:TEXT}}>{playing?<Pause className="w-3.5 h-3.5" strokeWidth={1.25} fill="currentColor"/>:<Play className="w-3.5 h-3.5" strokeWidth={1.25} fill="currentColor"/>}</button><div className="flex-1 flex items-center gap-px" style={{height:h,minWidth:0}}>{peaks.map((p,i)=>{const pl=i/peaks.length<progress;return <div key={i} className="flex-1" style={{height:`${Math.max(10,p*100)}%`,background:pl?IKB:DIM,minWidth:'1px',transition:'background 0.1s'}}/>;})}{peaks.length===0&&<div className="flex-1 italic" style={{color:FAINT,fontFamily:serif,fontSize:'11px'}}>recording unavailable</div>}</div></div>);}

export function ItemPickerPopup({availableItems,onPick,onClose}){return (<><div className="fixed inset-0 z-20" onClick={onClose}/><div className="absolute z-30 right-0 mt-1 min-w-64 max-h-64 overflow-auto etudes-scroll" style={{background:SURFACE,border:`1px solid ${LINE_STR}`,boxShadow:'0 4px 20px rgba(0,0,0,0.5)'}}>{availableItems.length===0&&<div className="px-4 py-3 text-xs italic" style={{color:FAINT,fontFamily:serif}}>No items available.</div>}{availableItems.map(it=>(<button key={it.id} onClick={()=>{onPick(it.id);onClose();}} className="w-full text-left px-4 py-2.5" style={{borderBottom:`1px solid ${LINE}`}}><div style={{fontSize:'13px',fontWeight:300}}>{displayTitle(it)}</div>{formatByline(it)&&<div className="italic mt-0.5" style={{color:MUTED,fontFamily:serif,fontSize:'11px'}}>{formatByline(it)}</div>}</button>))}</div></>);}

export function TargetEdit({target,onChange,small=false}){const [editing,setEditing]=useState(false);const [val,setVal]=useState('');const open=(e)=>{e.stopPropagation();setVal(target?String(target):'');setEditing(true);};const commit=()=>{const n=parseInt(val,10);onChange(Number.isFinite(n)&&n>0?n:null);setEditing(false);};if(editing){return (<input autoFocus value={val} onChange={e=>setVal(e.target.value.replace(/[^0-9]/g,''))} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')commit();else if(e.key==='Escape'){setEditing(false);}}} onClick={e=>e.stopPropagation()} className="font-mono tabular-nums focus:outline-none px-1.5 text-center" style={{background:SURFACE2,color:TEXT,border:`1px solid ${LINE_STR}`,width:'38px',fontSize:small?'10px':'11px'}} placeholder="min"/>);}if(target){return (<button onClick={open} className="font-mono tabular-nums" style={{color:'inherit',fontSize:'inherit',whiteSpace:'nowrap',letterSpacing:0}} title="Edit target">/ {target}′</button>);}return (<button onClick={open} className="uppercase target-hover-reveal" style={{color:FAINT,fontSize:'9px',letterSpacing:'0.2em',marginLeft:'4px'}} title="Set target">+ target</button>);}

export function TimeWithTarget({seconds,target,onTargetChange,format,small=false}){const ex=!!target&&seconds>=target*60;const col=ex?IKB:MUTED;return (<span className="inline-flex items-baseline gap-1.5" style={{fontFamily:mono,color:col,fontSize:small?'11px':'12px',fontWeight:300}}><span className="tabular-nums">{format(seconds)}</span><TargetEdit target={target} onChange={onTargetChange} small={small}/></span>);}

export function ItemTimeEditor({seconds,onCommit,onCancel,small=false}){const [val,setVal]=useState(String(Math.floor((seconds||0)/60)));const commit=()=>{onCommit(val);};return (<span className="inline-flex items-center gap-1" onClick={e=>e.stopPropagation()}><input autoFocus value={val} onChange={e=>setVal(e.target.value.replace(/[^0-9]/g,''))} onKeyDown={e=>{if(e.key==='Enter')commit();else if(e.key==='Escape'){onCancel();}}} className="font-mono tabular-nums focus:outline-none px-1.5 text-right" style={{background:SURFACE2,color:TEXT,border:`1px solid ${IKB}`,width:'48px',fontSize:small?'11px':'12px'}}/><span style={{color:MUTED,fontSize:'10px'}}>min</span><button onClick={commit} title="Save" style={{color:IKB,padding:'2px'}}><Check className="w-3 h-3" strokeWidth={2}/></button><button onClick={onCancel} title="Cancel" style={{color:FAINT,padding:'2px'}}><X className="w-3 h-3" strokeWidth={1.25}/></button></span>);}

export function fmtSpotTime(s){s=s||0;const m=Math.floor(s/60);const sec=s%60;return `${m}:${String(sec).padStart(2,'0')}`;}

export function PerformanceChip({perf,compact=false}){if(!perf||!perf.date)return null;const days=daysUntil(perf.date);if(days===null||days<-30)return null;let color,text;if(days<0){color=MUTED;text=`${Math.abs(days)}d ago`;}else if(days===0){color=WARM;text='today';}else if(days<=7){color=WARM;text=`${days}d`;}else if(days<=30){color=IKB;text=`${days}d`;}else{color=FAINT;text=`${days}d`;}const label=perf.label||'perf';return (<span className="inline-flex items-center gap-1 uppercase" title={`${label} · ${perf.date}`} style={{color,fontSize:compact?'9px':'10px',letterSpacing:'0.22em',padding:compact?'1px 5px':'2px 6px',border:`1px solid ${color}40`,background:(days<=7&&days>=0)?`${color}15`:'transparent'}}><Calendar className="w-2.5 h-2.5" strokeWidth={1.25}/>{label} · {text}</span>);}

export function SpotRow({spot,itemId,itemTimes,isActive,onStart,onStop,onRename,onDelete,onEditTime,dayClosed,compact=false}){const [editing,setEditing]=useState(false);const [val,setVal]=useState(spot.label);const [editingTime,setEditingTime]=useState(false);const time=getSpotTime(itemTimes,itemId,spot.id);const commit=()=>{if(val.trim())onRename(val.trim());else setVal(spot.label);setEditing(false);};return (<div className="group flex items-center gap-3 py-2 px-2" style={{background:isActive?IKB_SOFT:'transparent',borderLeft:isActive?`2px solid ${IKB}`:`2px solid transparent`}}><button onClick={()=>isActive?onStop():onStart()} disabled={dayClosed&&!isActive} className="shrink-0" style={{color:isActive?IKB:(dayClosed?FAINT:TEXT),cursor:(dayClosed&&!isActive)?'not-allowed':'pointer'}}>{isActive?<Pause className="w-3.5 h-3.5" strokeWidth={1.25} fill="currentColor"/>:<Play className="w-3.5 h-3.5" strokeWidth={1.25} fill="currentColor"/>}</button><Crosshair className="w-3 h-3 shrink-0" strokeWidth={1.25} style={{color:isActive?IKB:FAINT}}/>{editing?(<input autoFocus value={val} onChange={e=>setVal(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')commit();else if(e.key==='Escape'){setVal(spot.label);setEditing(false);}}} className="flex-1 focus:outline-none pb-0.5" style={{background:'transparent',color:TEXT,borderBottom:`1px solid ${LINE_STR}`,fontFamily:serif,fontSize:compact?'13px':'14px',fontWeight:300}}/>):(<span onDoubleClick={()=>setEditing(true)} className="flex-1 cursor-text" style={{fontFamily:serif,fontSize:compact?'13px':'14px',fontWeight:300}}>{spot.label}</span>)}{spot.bpmTarget&&<span className="font-mono tabular-nums shrink-0" style={{color:FAINT,fontSize:'10px'}}>♩ {spot.bpmTarget}</span>}{editingTime?(<ItemTimeEditor seconds={time} onCommit={(v)=>{onEditTime&&onEditTime(v);setEditingTime(false);}} onCancel={()=>setEditingTime(false)} small/>):(<><span className="font-mono tabular-nums shrink-0" style={{color:time>0?MUTED:FAINT,fontSize:'11px',fontWeight:300}}>{time>0?fmtSpotTime(time):'—'}</span>{!dayClosed&&onEditTime&&<button onClick={()=>setEditingTime(true)} className="target-hover-reveal shrink-0" style={{color:FAINT}} title="Edit minutes"><Pencil className="w-3 h-3" strokeWidth={1.25}/></button>}</>)}{!editing&&!editingTime&&(<><button onClick={()=>setEditing(true)} className="target-hover-reveal shrink-0" style={{color:FAINT}} title="Rename"><Pencil className="w-3 h-3" strokeWidth={1.25}/></button><button onClick={onDelete} className="target-hover-reveal shrink-0" style={{color:FAINT}} title="Delete spot"><X className="w-3 h-3" strokeWidth={1.25}/></button></>)}</div>);}

export function SpotsBlock({item,itemTimes,activeItemId,activeSpotId,startItem,stopItem,addSpot,updateSpot,deleteSpot,editSpotTime,dayClosed}){const spots=item.spots||[];return (<div><div className="uppercase mb-2 flex items-center gap-1.5" style={{color:FAINT,fontSize:'10px',letterSpacing:'0.25em'}}><Crosshair className="w-3 h-3" strokeWidth={1.25} style={{color:IKB}}/> Spots {spots.length>0&&<span style={{color:DIM,letterSpacing:'0.2em'}}>· {spots.length}</span>}</div>{spots.length>0&&(<div style={{background:SURFACE2,border:`1px solid ${LINE}`}}>{spots.map((s,idx)=>(<div key={s.id} style={{borderBottom:idx<spots.length-1?`1px solid ${LINE}`:'none'}}><SpotRow spot={s} itemId={item.id} itemTimes={itemTimes} isActive={activeItemId===item.id&&activeSpotId===s.id} onStart={()=>startItem(item.id,s.id)} onStop={stopItem} onRename={(label)=>updateSpot(item.id,s.id,{label})} onDelete={()=>deleteSpot(item.id,s.id)} onEditTime={editSpotTime?(v)=>editSpotTime(item.id,s.id,v):undefined} dayClosed={dayClosed}/></div>))}</div>)}<button onClick={()=>addSpot(item.id,'New spot')} className="uppercase flex items-center gap-1.5 mt-2 italic" style={{color:MUTED,fontFamily:serif,fontSize:'12px'}}><Plus className="w-3 h-3 not-italic" strokeWidth={1.25}/> Add spot</button></div>);}
